### PR TITLE
Add gargoyle-nix package

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by ryantrinkle** [comment]
@danharaj Would you mind reviewing and merging?

**Comment by 3noch** [comment]
@danharaj How about `gargoyle-nix-postgres`? ;)

**Comment by ryantrinkle** [comment]
@3noch @danharaj Not sure which of you should merge, but please merge away.

**Comment by danharaj** [comment]
@3noch Could you rename the package and merge?

**Comment by 3noch** [comment]
@danharaj Yep.

**Comment by 3noch** [comment]
@danharaj I'm thinking `gargoyle-postgresql-nix` would be better since it matches the module import `Gargoyle.PostgreSQL.Nix`.

**Comment by danharaj** [comment]
Sure

**Pull request merged**
