### PR TITLE
gargoyle-postgresql-connect: Remove groundhog dependency

### LINKED ISSUE #26: gargoyle-postgresql-connect should not depend on groundhog

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #26

### CODE REVIEW

**Comment by 3noch** [comment]
Still testing this...

**Comment by 3noch** [comment]
Ok seems fine.

**Comment by alexfmpe** [comment]
Oh goodie - now I can get rid of a `groundhog-postgresql` dependency on a certain Beam-based project

**Comment by ryantrinkle** [comment]
Thanks!

**Pull request merged**
